name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create config.json
      run: |
        echo '{
          "SERVICE_ID": "${{ secrets.EMAILJS_SERVICE_ID }}",
          "TEMPLATE_ID": "${{ secrets.EMAILJS_TEMPLATE_ID }}",
          "PUBLIC_KEY": "${{ secrets.EMAILJS_PUBLIC_KEY }}"
        }' > config.json

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .